// Use static timestamps for deterministic tests
const MOCK_TIMESTAMP = '2025-01-01T12:00:00.000Z';
const MOCK_TIMESTAMP_EARLIER = '2025-01-01T11:55:00.000Z';

const mockAccount = {
  id: 'acct_mock_1',
  username: 'coho',
  acct: 'coho@mock.social',
  display_name: 'Coho Bot',
  locked: false,
  bot: false,
  created_at: MOCK_TIMESTAMP,
  note: '<p>Resident test account</p>',
  url: 'https://tech.lgbt/@coho',
  avatar: '/assets/icons/icon-128.png',
  avatar_static: '/assets/icons/icon-128.png',
  header: '/assets/icons/icon-512.png',
  header_static: '/assets/icons/icon-512.png',
  followers_count: 420,
  following_count: 133,
  statuses_count: 2048,
  emojis: [],
  fields: [],
};

const basePost = {
  id: 'post_mock_1',
  created_at: MOCK_TIMESTAMP,
  in_reply_to_id: null,
  in_reply_to_account_id: null,
  sensitive: false,
  spoiler_text: '',
  visibility: 'public',
  uri: 'https://tech.lgbt/users/coho/statuses/post_mock_1',
  url: 'https://tech.lgbt/@coho/post_mock_1',
  replies_count: 3,
  reblogs_count: 2,
  favourites_count: 5,
  favourited: false,
  reblogged: false,
  muted: false,
  bookmarked: false,
  pinned: false,
  content: '<p>Welcome to the mocked timeline!</p>',
  reblog: null,
  application: {
    name: 'Coho Test Harness',
    website: null,
  },
  account: mockAccount,
  media_attachments: [],
  mentions: [],
  tags: [],
  emojis: [],
  card: null,
  poll: null,
  reply_to: null,
  ancestors: [],
  thread_continuation: [],
};

const secondaryPost = {
  ...basePost,
  id: 'post_mock_2',
  created_at: MOCK_TIMESTAMP_EARLIER,
  content: '<p>Timeline post number two.</p>',
  replies_count: 1,
  favourites_count: 2,
};

export const mockTimelinePosts = [basePost, secondaryPost];

export const mockBookmarks = [
  {
    ...basePost,
    id: 'bookmark_mock_1',
    content: '<p>Saved post from your bookmarks.</p>',
    bookmarked: true,
  },
];

export const mockFavorites = [
  {
    ...basePost,
    id: 'favorite_mock_1',
    content: '<p>Your favorited post appears here.</p>',
    favourited: true,
  },
];

export const mockNotifications = [
  {
    id: 'notify_follow_1',
    type: 'follow',
    created_at: MOCK_TIMESTAMP,
    account: mockAccount,
    status: basePost,
  },
  {
    id: 'notify_favourite_1',
    type: 'favourite',
    created_at: MOCK_TIMESTAMP,
    account: mockAccount,
    status: secondaryPost,
  },
  {
    id: 'notify_mention_1',
    type: 'mention',
    created_at: MOCK_TIMESTAMP,
    account: mockAccount,
    status: {
      ...basePost,
      id: 'post_mention_1',
      content: '<p>@you This is a mention notification!</p>',
    },
  },
];

export const mockSearchResult = {
  query: 'Mastodon',
  accounts: [
    {
      id: 'acct_search_1',
      username: 'searchbot',
      acct: 'searchbot@mock.social',
      display_name: 'Search Bot',
      note: '<p>I love search results.</p>',
      url: 'https://tech.lgbt/@searchbot',
      avatar: '/assets/icons/icon-128.png',
      avatar_static: '/assets/icons/icon-128.png',
    },
  ],
  statuses: mockTimelinePosts,
  hashtags: [
    {
      name: 'coho',
      url: 'https://tech.lgbt/tags/coho',
    },
  ],
};

export const mockTrendingStatuses = mockTimelinePosts;

export const mockTrendingLinks = [
  {
    url: 'https://coho.app/blog/mock-news',
    title: 'Coho Mock News',
    description: 'Daily digest generated by the local mock server.',
    image: '/assets/screenshots/home.png',
  },
];

export const mockAccountProfile = mockAccount;

export const mockInstanceInfo = {
  title: 'Tech.LGBT Mock Instance',
  thumbnail: '/assets/icons/icon-192-maskable.png',
  description: '<p>Mock description for the local test instance.</p>',
  configuration: {
    statuses: {
      max_characters: 500,
      max_media_attachments: 4,
      characters_reserved_per_url: 23,
    },
    media_attachments: {
      supported_mime_types: [
        'image/jpeg',
        'image/png',
        'image/gif',
        'image/webp',
        'video/mp4',
        'video/webm',
      ],
      image_size_limit: 10485760,
      image_matrix_limit: 16777216,
      video_size_limit: 41943040,
      video_frame_rate_limit: 60,
      video_matrix_limit: 2304000,
    },
    polls: {
      max_options: 4,
      max_characters_per_option: 50,
      min_expiration: 300,
      max_expiration: 2629746,
    },
  },
};

export const mockMediaAttachment = {
  id: 'media_mock_1',
  type: 'image',
  url: 'https://files.tech.lgbt/mock-image.png',
  preview_url: 'https://files.tech.lgbt/mock-image-preview.png',
  remote_url: null,
  description: '',
  blurhash: 'LEHV6nWB2yk8pyo0adR*.7kCMdnj',
  meta: {
    original: {
      width: 1200,
      height: 800,
      size: '1200x800',
      aspect: 1.5,
    },
  },
};

export const mockTrendingTags = [
  {
    name: 'coho',
    url: 'https://tech.lgbt/tags/coho',
    history: [
      {
        day: '1668297600',
        uses: '100',
        accounts: '50',
      },
    ],
  },
];

export const mockEditHistory = [
  {
    content: '<p>Welcome to the mocked timeline! (edited)</p>',
    spoiler_text: '',
    sensitive: false,
    created_at: MOCK_TIMESTAMP,
    account: mockAccount,
    poll: null,
    media_attachments: [],
    emojis: [],
  },
  {
    content: '<p>Welcome to the mocked timeline!</p>',
    spoiler_text: '',
    sensitive: false,
    created_at: MOCK_TIMESTAMP_EARLIER,
    account: mockAccount,
    poll: null,
    media_attachments: [],
    emojis: [],
  },
];
