import { test, expect } from '@playwright/test';
import { bootstrapApp, navigateTo } from './test-utils';

test.describe('Post Deep Linking', () => {
  test.beforeEach(async ({ page }) => {
    await bootstrapApp(page);
  });

  test('can navigate to post by ID', async ({ page }) => {
    // Navigate to a post by its ID
    await navigateTo(page, '/post/post_mock_1');

    // Wait for the post-detail component to load
    await page.waitForSelector('post-detail');

    // Should show the timeline-item with the post content
    await expect(page.locator('timeline-item#main')).toBeVisible();

    // Check that the post content is displayed
    await expect(page.locator('timeline-item#main')).toContainText(
      'Welcome to the mocked timeline'
    );
  });

  test('can navigate to post via notification ID', async ({ page }) => {
    // Navigate using notification_id (simulates push notification click)
    await navigateTo(
      page,
      '/post/notification?notification_id=notify_mention_1'
    );

    // Wait for the post-detail component to load
    await page.waitForSelector('post-detail');

    // Should show the timeline-item with the mention content
    await expect(page.locator('timeline-item#main')).toBeVisible();

    // Check that the mention post content is displayed
    await expect(page.locator('timeline-item#main')).toContainText(
      'This is a mention notification'
    );
  });

  test('shows skeleton while loading', async ({ page }) => {
    // Slow down network to catch the loading state
    await page.route('**/api/v1/statuses/**', async (route) => {
      await new Promise((resolve) => setTimeout(resolve, 500));
      await route.continue();
    });

    // Start navigation but don't await
    navigateTo(page, '/post/post_mock_1');

    // Should show skeleton briefly
    const skeleton = page.locator('md-skeleton-card');
    await expect(skeleton).toBeVisible({ timeout: 1000 });
  });

  test('shows error state for non-existent post', async ({ page }) => {
    // Navigate to a non-existent post
    await navigateTo(page, '/post/non_existent_post_id');

    // Wait for the post-detail component
    await page.waitForSelector('post-detail');

    // Should show error state
    await expect(page.locator('post-detail')).toContainText(
      'Failed to load post'
    );
  });

  test('shows error for non-existent notification', async ({ page }) => {
    // Navigate with a non-existent notification ID
    await navigateTo(
      page,
      '/post/notification?notification_id=non_existent_notification'
    );

    // Wait for the post-detail component
    await page.waitForSelector('post-detail');

    // Should show error or redirect
    // The component should handle this gracefully
    await expect(page.locator('post-detail')).toContainText(
      'Failed to load post'
    );
  });

  test('legacy query string navigation still works', async ({ page }) => {
    // Encode a post object as query string (legacy behavior)
    const mockPost = {
      id: 'legacy_post',
      content: 'Legacy navigation test',
      account: {
        id: 'test_account',
        username: 'testuser',
        display_name: 'Test User',
        avatar: '/assets/icons/icon-128.png',
      },
      created_at: new Date().toISOString(),
      replies_count: 0,
      reblogs_count: 0,
      favourites_count: 0,
    };

    const encoded = encodeURIComponent(JSON.stringify(mockPost));
    await navigateTo(page, `/home/post?${encoded}`);

    // Wait for the post-detail component
    await page.waitForSelector('post-detail');

    // Should show the post content
    await expect(page.locator('timeline-item#main')).toBeVisible();
  });
});

test.describe('Notification Click URL Generation', () => {
  // These tests verify the URL patterns that would be generated by the service worker
  // Since we can't easily test SW events in Playwright, we test the resulting URLs

  test('mention notification would deep link to post', async ({ page }) => {
    await bootstrapApp(page);

    // Simulate what the SW would do for a mention notification
    const notificationId = 'notify_mention_1';
    const expectedUrl = `/post/notification?notification_id=${notificationId}`;

    await navigateTo(page, expectedUrl);
    await page.waitForSelector('post-detail');

    // Should load the post from the notification
    await expect(page.locator('timeline-item#main')).toBeVisible();
  });

  test('favourite notification would deep link to post', async ({ page }) => {
    await bootstrapApp(page);

    // Simulate what the SW would do for a favourite notification
    const notificationId = 'notify_favourite_1';
    const expectedUrl = `/post/notification?notification_id=${notificationId}`;

    await navigateTo(page, expectedUrl);
    await page.waitForSelector('post-detail');

    // Should load the post from the notification
    await expect(page.locator('timeline-item#main')).toBeVisible();
  });
});
