import { LitElement } from 'lit';
import { type ProfilePostsFilter } from '../services/account';
import '../components/timeline-item';
import '../components/md/md-dialog';
import '../components/md/md-text-area';
import '../components/md/md-dropdown';
import '../components/md/md-menu';
import '../components/md/md-menu-item';
import '../components/md/md-icon';
import '../components/md/md-icon-button';
import '../components/report-dialog';
import type { ReportSubmitDetail } from '../components/report-dialog';
import type { Account } from '../mastodon/types';
import '../components/md/md-skeleton';
import '../components/md/md-segmented-button';
import '../components/md/md-divider';
import '../components/md/md-badge';
import { Post } from '../interfaces/Post';
export declare class AppProfile extends LitElement {
    user: Account | undefined;
    posts: Post[];
    followed: boolean;
    following: boolean;
    muted: boolean;
    blocked: boolean;
    selectedPost: Post | undefined;
    isOwnProfile: boolean;
    showReportDialog: boolean;
    activeSegment: ProfilePostsFilter;
    loadingPosts: boolean;
    private previewContent;
    private editDialog;
    private contentTextArea;
    static styles: import("lit").CSSResult[];
    firstUpdated(): Promise<void>;
    follow(): Promise<void>;
    reloadPosts(): Promise<void>;
    handleSegmentChange(e: CustomEvent<{
        value: string;
    }>): Promise<void>;
    unfollow(): Promise<void>;
    mute(): Promise<void>;
    unmute(): Promise<void>;
    block(): Promise<void>;
    unblock(): Promise<void>;
    openReportDialog(): void;
    handleReportSubmit(e: CustomEvent<ReportSubmitDetail>): Promise<void>;
    handleReportCancel(): void;
    editPost(tweet: Post): void;
    confirmEdit(): Promise<void>;
    private goToFollowers;
    private goToFollowing;
    render(): import("lit-html").TemplateResult<1>;
}
