import { LitElement } from 'lit';
import './md/md-icon-button';
import './md/md-icon';
import './md/md-skeleton';
export declare class ImagePreviewDialog extends LitElement {
  open: boolean;
  src: string;
  alt: string;
  width: number;
  height: number;
  loaded: boolean;
  private swipeOffset;
  private isDragging;
  private isClosingWithSwipe;
  private startY;
  private startTime;
  dialog: HTMLDialogElement;
  container: HTMLElement;
  closeButton: HTMLElement;
  static styles: import('lit').CSSResult;
  connectedCallback(): void;
  disconnectedCallback(): void;
  updated(changedProperties: Map<string, unknown>): void;
  private handlePreviewImage;
  private handleImageLoad;
  private handleGenerateAlt;
  private close;
  private handleBackdropClick;
  private handleTouchStart;
  private handleTouchMove;
  private handleTouchEnd;
  private closeWithSwipeAnimation;
  private resetSwipePosition;
  render(): import('lit-html').TemplateResult<1>;
}
