import { LitElement } from 'lit';
import './md/md-dialog.js';
import './md/md-button.js';
import './md/md-text-area.js';
import './md/md-skeleton.js';
export declare class MediaEditDialog extends LitElement {
  open: boolean;
  imageSrc: string;
  description: string;
  mediaId: string;
  imageLoaded: boolean;
  generating: boolean;
  promptAPIAvailable: boolean;
  selectedFilter: string;
  filterThumbnails: Record<string, string>;
  previewUrl: string;
  editedBlob: Blob | null;
  isProcessing: boolean;
  isUploading: boolean;
  connectedCallback(): void;
  static styles: import('lit').CSSResult;
  willUpdate(changedProperties: Map<string, unknown>): void;
  private generateThumbnails;
  private handleImageLoad;
  private handleFilterSelect;
  private handleSave;
  completeUpload(success: boolean): void;
  private close;
  private handleDialogHide;
  private handleDialogShow;
  private handleGenerateAlt;
  private getCurrentPreviewUrl;
  render(): import('lit-html').TemplateResult<1>;
}
