import { LitElement } from 'lit';
import { Settings } from '../services/settings';
import { Post } from '../interfaces/Post';
import type { Account } from '../mastodon/types';
import { TimelineItemHandlers, TimelineItemState } from './timeline-renderers';
import './report-dialog';
import type { ReportSubmitDetail } from './report-dialog';
export declare class TimelineItem extends LitElement {
  tweet: Post | undefined;
  show: boolean;
  showreply: boolean;
  guestMode: boolean;
  focused: boolean;
  isBoosted: boolean;
  isReblogged: boolean;
  isBookmarked: boolean;
  threadExpanded: boolean;
  threadPosts: Post[];
  loadingThread: boolean;
  settings: Settings | undefined;
  currentUser: Account | null;
  showReportDialog: boolean;
  reportAccountId: string;
  reportAccountAcct: string;
  reportStatusId: string | undefined;
  isOnDeviceTranslateAvailable: boolean;
  device: 'mobile' | 'desktop';
  static styles: import('lit').CSSResult[];
  showThread(): Promise<void>;
  firstUpdated(): Promise<void>;
  disconnectedCallback(): void;
  private _handleKeydown;
  /**
   * Show login prompt for guests trying to use auth-required features
   */
  private showLoginPrompt;
  favorite(id: string): Promise<void>;
  reblog(id: string): Promise<void>;
  bookmark(id: string): Promise<void>;
  replies(): Promise<void>;
  shareStatus(tweet: Post | null): Promise<void>;
  openPost(): Promise<void>;
  openParentPost(): Promise<void>;
  deleteStatus(): Promise<void>;
  initEditStatus(): Promise<void>;
  viewSensitive(): void;
  viewThreadSensitive(id: string): void;
  viewReplySensitive(): void;
  openLinkCard(url: string): void;
  summarizePost(postContent: string | null): Promise<void>;
  translatePost(postContent: string | null): Promise<void>;
  muteUser(accountId: string): Promise<void>;
  blockUser(accountId: string): Promise<void>;
  reportUser(accountId: string, accountAcct: string, statusId?: string): void;
  handleReportSubmit(e: CustomEvent<ReportSubmitDetail>): Promise<void>;
  handleReportCancel(): void;
  getHandlers(): TimelineItemHandlers;
  getState(): TimelineItemState;
  render(): import('lit-html').TemplateResult<1>;
}
